{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-client",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "gevxuybc4nac7dmfyxlry26xfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-client-0.3.jar",
          "url": "conclave-client-0.3.jar",
          "size": 11935,
          "sha512": "c876aff4e3eba1da73c1dbb258dcd663459426fe1192e5b230d494281335f5b135f847f3cc49e3194d4b7082d2f3b4bc4b5ebeecdc051a4439824786c8d702f0",
          "sha256": "f9a29ca69423e8200da12cbf96f7efd47f31928225d8817d1751169f94e790ed",
          "sha1": "e63c8a699c4b58a4057f187f55508632a12e980c",
          "md5": "be189d20da9567b184e2b6615677498f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-client-0.3.jar",
          "url": "conclave-client-0.3.jar",
          "size": 11935,
          "sha512": "c876aff4e3eba1da73c1dbb258dcd663459426fe1192e5b230d494281335f5b135f847f3cc49e3194d4b7082d2f3b4bc4b5ebeecdc051a4439824786c8d702f0",
          "sha256": "f9a29ca69423e8200da12cbf96f7efd47f31928225d8817d1751169f94e790ed",
          "sha1": "e63c8a699c4b58a4057f187f55508632a12e980c",
          "md5": "be189d20da9567b184e2b6615677498f"
        }
      ]
    }
  ]
}
