{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-common",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "gevxuybc4nac7dmfyxlry26xfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-mail",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-common-0.3.jar",
          "url": "conclave-common-0.3.jar",
          "size": 198737,
          "sha512": "4ddcc23241c8addf4aebbf55653f78f5bbe737896976dae499fee6f6ff561abfe19533366f51cd6d51aea23c2f323de0f42d91aad06e1b3966a6ec55ff2d6546",
          "sha256": "59a1ccd3bd5dd9b09e3e566676e2837e1de47823c16171ef346615de33ed5842",
          "sha1": "fad53138e4495a75658e0f528e79e1146dfb4bd0",
          "md5": "6e17c4fafda55a1803d0746a3ae54263"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.10.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "net.i2p.crypto",
          "module": "eddsa",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "conclave-mail",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-common-0.3.jar",
          "url": "conclave-common-0.3.jar",
          "size": 198737,
          "sha512": "4ddcc23241c8addf4aebbf55653f78f5bbe737896976dae499fee6f6ff561abfe19533366f51cd6d51aea23c2f323de0f42d91aad06e1b3966a6ec55ff2d6546",
          "sha256": "59a1ccd3bd5dd9b09e3e566676e2837e1de47823c16171ef346615de33ed5842",
          "sha1": "fad53138e4495a75658e0f528e79e1146dfb4bd0",
          "md5": "6e17c4fafda55a1803d0746a3ae54263"
        }
      ]
    }
  ]
}
