{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "enclave-utils",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "gevxuybc4nac7dmfyxlry26xfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "enclave-utils-0.3.jar",
          "url": "enclave-utils-0.3.jar",
          "size": 21034,
          "sha512": "a70da16617b96e90f919203814d6a20342947f9328a2fc273071f0607647d2169285b3f287fa4111cddd2587a9991c60e02f1046a7c71d89b670d61c0ee0d7d6",
          "sha256": "c907e9f87390e36c881effbf3def0f457ea4f31000705d7357782d755abf8010",
          "sha1": "4eff84872a2cc21802896c88c131096f9cdff784",
          "md5": "f6862ae303a7e4d82bd80b901574aac9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.graalvm.sdk",
          "module": "graal-sdk",
          "version": {
            "requires": "20.1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "enclave-utils-0.3.jar",
          "url": "enclave-utils-0.3.jar",
          "size": 21034,
          "sha512": "a70da16617b96e90f919203814d6a20342947f9328a2fc273071f0607647d2169285b3f287fa4111cddd2587a9991c60e02f1046a7c71d89b670d61c0ee0d7d6",
          "sha256": "c907e9f87390e36c881effbf3def0f457ea4f31000705d7357782d755abf8010",
          "sha1": "4eff84872a2cc21802896c88c131096f9cdff784",
          "md5": "f6862ae303a7e4d82bd80b901574aac9"
        }
      ]
    }
  ]
}
