{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-testing",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "gevxuybc4nac7dmfyxlry26xfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-enclave",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "conclave-host",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-testing-0.3.jar",
          "url": "conclave-testing-0.3.jar",
          "size": 18010,
          "sha512": "6f43e4e719cc23c4896c881d26b0778bb08157474501472f01ef2e25aa7e6773a0572fa45588f87e028606bb7ad239b2f4c36bbda26443d087be64d6b24e0b69",
          "sha256": "10f4ae36955b5d897fd81eed063715de1d4d158bc6b1ab3dd4f01e96549b451c",
          "sha1": "f4d93afcb6061b1ddaf27bfac07ccb31cc8f0c60",
          "md5": "3057cac60f33cf2e5c44a6a7607762b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "conclave-enclave",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "conclave-host",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-testing-0.3.jar",
          "url": "conclave-testing-0.3.jar",
          "size": 18010,
          "sha512": "6f43e4e719cc23c4896c881d26b0778bb08157474501472f01ef2e25aa7e6773a0572fa45588f87e028606bb7ad239b2f4c36bbda26443d087be64d6b24e0b69",
          "sha256": "10f4ae36955b5d897fd81eed063715de1d4d158bc6b1ab3dd4f01e96549b451c",
          "sha1": "f4d93afcb6061b1ddaf27bfac07ccb31cc8f0c60",
          "md5": "3057cac60f33cf2e5c44a6a7607762b3"
        }
      ]
    }
  ]
}
