{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-enclave",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "gevxuybc4nac7dmfyxlry26xfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-enclave-0.3.jar",
          "url": "conclave-enclave-0.3.jar",
          "size": 50157,
          "sha512": "10f6401174dbb46ff4d239a0ef5eaaaa91d9a267af20b50781ece4117c9b23c7e81d09bd7b1126d7b5cbf81af3aac4d2e5b83cdeeb956cdbce6ad061b7f1613b",
          "sha256": "af285100271ec68e249e34a159597e30cf99f024f82f692246fa0321afa9f8f4",
          "sha1": "9e27dcd7416d9ed67a54abd690a0b475090d2175",
          "md5": "661fdd7276d592c35928ff9d9e2ac48f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.graalvm.sdk",
          "module": "graal-sdk",
          "version": {
            "requires": "20.1.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.r3.conclave",
          "module": "conclave-common",
          "version": {
            "requires": "0.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-enclave-0.3.jar",
          "url": "conclave-enclave-0.3.jar",
          "size": 50157,
          "sha512": "10f6401174dbb46ff4d239a0ef5eaaaa91d9a267af20b50781ece4117c9b23c7e81d09bd7b1126d7b5cbf81af3aac4d2e5b83cdeeb956cdbce6ad061b7f1613b",
          "sha256": "af285100271ec68e249e34a159597e30cf99f024f82f692246fa0321afa9f8f4",
          "sha1": "9e27dcd7416d9ed67a54abd690a0b475090d2175",
          "md5": "661fdd7276d592c35928ff9d9e2ac48f"
        }
      ]
    }
  ]
}
