{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "conclave-mail",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "gevxuybc4nac7dmfyxlry26xfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "conclave-mail-0.3.jar",
          "url": "conclave-mail-0.3.jar",
          "size": 144042,
          "sha512": "fc5c8adf9ec9974889d748de23e3c72623aa456d28d184540d633db6d211c19ca86b75afb8c0945badad1e3b42c9e4a3758568ca40bf8cd0948fca9bb5977f53",
          "sha256": "7f90b3f596ece0e1036fe3dc52536d7fd9de883b7f62dff66bfbd893972c278e",
          "sha1": "9250535c1f29a9697948db4b1169635f88502327",
          "md5": "ca187b31ef3a1f8bafaa45372f369550"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conclave-mail-0.3.jar",
          "url": "conclave-mail-0.3.jar",
          "size": 144042,
          "sha512": "fc5c8adf9ec9974889d748de23e3c72623aa456d28d184540d633db6d211c19ca86b75afb8c0945badad1e3b42c9e4a3758568ca40bf8cd0948fca9bb5977f53",
          "sha256": "7f90b3f596ece0e1036fe3dc52536d7fd9de883b7f62dff66bfbd893972c278e",
          "sha1": "9250535c1f29a9697948db4b1169635f88502327",
          "md5": "ca187b31ef3a1f8bafaa45372f369550"
        }
      ]
    }
  ]
}
