{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "macos-sign-tool",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "gevxuybc4nac7dmfyxlry26xfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "macos-sign-tool-0.3.jar",
          "url": "macos-sign-tool-0.3.jar",
          "size": 88725,
          "sha512": "9f30550f2d589b953807342b935206fa650ee025b9aa1a25b25d2fb89624b2301d35663f72382ea8a9f5771df224fdbe3d0db7ace21654e886b22ff2911cba50",
          "sha256": "1182ebca719e138227068051d7758ec495ad06fc780e061785dac8bf5c6d9535",
          "sha1": "c2adf26ff6eccce26af2294c0cefbd6bd56b8d26",
          "md5": "86df9c7e451bcf8bfc284c58ec1672c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "macos-sign-tool-0.3.jar",
          "url": "macos-sign-tool-0.3.jar",
          "size": 88725,
          "sha512": "9f30550f2d589b953807342b935206fa650ee025b9aa1a25b25d2fb89624b2301d35663f72382ea8a9f5771df224fdbe3d0db7ace21654e886b22ff2911cba50",
          "sha256": "1182ebca719e138227068051d7758ec495ad06fc780e061785dac8bf5c6d9535",
          "sha1": "c2adf26ff6eccce26af2294c0cefbd6bd56b8d26",
          "md5": "86df9c7e451bcf8bfc284c58ec1672c1"
        }
      ]
    }
  ]
}
