{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-host-shared",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "gevxuybc4nac7dmfyxlry26xfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "native-host-shared-0.3.jar",
          "url": "native-host-shared-0.3.jar",
          "size": 127235,
          "sha512": "f85a1b5d07fd8e8b988b022057f0df01a0a1bc95dfaac295a5f905666f1a131d40793c2d9cb80777a6ed94551a2f562277871f7d3715427b4ceb15d9de900dff",
          "sha256": "1e9d0fc8bb7def082e30830fc9cff3fab63f73e9ecf0ac3bce5e7794485a85cd",
          "sha1": "1f389951cf961e1c73d53a54cb2e9d957fd4d773",
          "md5": "b2e23b3ded1307455f42bc8d13cb9205"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.61"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-host-shared-0.3.jar",
          "url": "native-host-shared-0.3.jar",
          "size": 127235,
          "sha512": "f85a1b5d07fd8e8b988b022057f0df01a0a1bc95dfaac295a5f905666f1a131d40793c2d9cb80777a6ed94551a2f562277871f7d3715427b4ceb15d9de900dff",
          "sha256": "1e9d0fc8bb7def082e30830fc9cff3fab63f73e9ecf0ac3bce5e7794485a85cd",
          "sha1": "1f389951cf961e1c73d53a54cb2e9d957fd4d773",
          "md5": "b2e23b3ded1307455f42bc8d13cb9205"
        }
      ]
    }
  ]
}
